name: 'Filter IP'
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: mkdir
        run: mkdir build
      - name: cmake build
        run: cmake -Bbuild -DPATCH_VERSION=${{ github.run_number }} -DBUILD_TESTS=ON ${{github.workspace}}/hw2/
      - name: cmake make
        run: cmake --build build/
      - run: cmake --build build/ --target package
      - name: Run unit tests
        run: ./build/tests/test_filter_ip